### ISSUE TITLE
Activity sea non funziona

### ISSUE THREAD

**Issue by enricofab** [marcurius91/unisannio-reboot#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcurius91** [comment]
Bug fixed in
https://github.com/marcurius91/unisannio-reboot/commit/d111fd4e524447914fd73d9689ac64f1f96ce5c3
