### ISSUE TITLE
Giurisprudenza: errore in visualizzazione avvisi

### ISSUE THREAD

**Issue by prokekko93** [marcurius91/unisannio-reboot#10]
**Describe the bug**
L'Activity di Giurisprudenza non funziona quando richiamata.

**To Reproduce**
1. Go to 'Menu'
2. Click on 'Giurisprudenza Avvisi Studenti'
3. See error

**Expected behavior**
Visualizzazione degli avvisi di Giurisprudenza

**Smartphone (please complete the following information):**
 - Device: Asus Zenfone 3
 - OS: Android 7.0

**Comment by enricofab** [comment]
bug fixed in commit d8ade25
