### ISSUE TITLE
Activity Ateneo_Avvisi

### ISSUE THREAD

**Issue by marcurius91** [marcurius91/unisannio-reboot#2]
**Describe the bug**
Quando si cerca di visualizzare gli avvisi ateneo cliccando sull'apposito tab nel menu resta in caricamento e non esce nullua
**To Reproduce**
1. Menu
2. Ateneo Avvisi Studento
3. See error (Nothing showed)

**Expected behavior**
Visualizzare gli avvisi ateneo
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiamiu
 - OS: android 8.1

**Comment by enricofab** [comment]
bug fixed in commit 
https://github.com/marcurius91/unisannio-reboot/commit/d679c830531b623fd64884428d1b3da414a7fd74
