### ISSUE TITLE
Premendo su Ateneo nel menu l'app crasha

### ISSUE THREAD

**Issue by marcurius91** [marcurius91/unisannio-reboot#5]
**Describe the bug**
Premendo su Ateneo nel menu l'app crasha

**To Reproduce**
1. Go to menu
2. Click on Ateneo
3. See error

**Expected behavior**
Gli altri tasti, non sono premibili.
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung S5
 - OS: Android 7

**Comment by enricofab** [comment]
bug fixed on commit https://github.com/marcurius91/unisannio-reboot/commit/d679c830531b623fd64884428d1b3da414a7fd74
