### ISSUE TITLE
Bug trovati con analisi lint

### ISSUE THREAD

**Issue by prokekko93** [marcurius91/unisannio-reboot#8]
**Describe the bug**
Unresolved class 'ScienzeFragment'. Validates resource references inside Android XML files.
**To Reproduce**
1. Run inspection with Lint

**Desktop (please complete the following information):**
 - OS: [Windows]

**Smartphone (please complete the following information):**
 - OS: [Android]

**Comment by marcurius91** [comment]
Risolto in https://github.com/marcurius91/unisannio-reboot/commit/f6f875682ced0ef77e2bed5da0ba6fa3ef9cd135
